window.fixedTimeZone = true;
window.timeZone = 'UTC';
window.timeZoneOffset = 0;
window.blockly = window.blockly || {};
window.blockly.js = window.blockly.js || {};
window.blockly.js.blockly = window.blockly.js.blockly || {};
window.translations = window.translations || {};
window.translations.localesKeys = ['en_us','pt_br'];
window.translations.localesRef =  {"en*":"en_us","pt*":"pt_br","*":"pt_br"};
// document.write("<script src='js/blockly/MutualAuth.blockly.js?1646657174000'></script>")