import '../webapp/js/customModules';
import '../webapp/js/customStateProvider.js';
import 'cronapp-framework-js/dist/js/stateProvider.js';
import 'jquery/dist/jquery.min.js';
import 'bootstrap/dist/js/bootstrap.min.js';
import 'angular/angular.min.js';
import 'chart.js/dist/Chart.min.js';
import 'angular-chart.js/dist/angular-chart.min.js';
import 'angular-ui-router/release/angular-ui-router.min.js';
import 'angular-cookies/angular-cookies.min.js';
import 'angular-resource/angular-resource.min.js';
import 'angular-sanitize/angular-sanitize.min.js';
import 'angular-ui-bootstrap/ui-bootstrap.min.js';
import 'angular-ui-bootstrap/ui-bootstrap-tpls.min.js';
import 'ui-select-infinity/lib/index.js';
import 'raphael/raphael.min.js';
import 'justgage/justgage.js';
import 'angular-translate/dist/angular-translate.min.js';
import 'angular-translate-loader-static-files/angular-translate-loader-static-files.min.js';
import 'angular-translate-storage-cookie/angular-translate-storage-cookie.min.js';
import 'angular-translate-storage-local/angular-translate-storage-local.min.js';
import 'angular-translate-handler-log/angular-translate-handler-log.min.js';
import 'angular-dynamic-locale/dist/tmhDynamicLocale.js';
import 'angular-ui-notification/dist/angular-ui-notification.min.js';
import 'ng-file-upload/dist/ng-file-upload.min.js';
import 'moment/min/moment-with-locales.min.js';
import 'eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js';
import 'cpf_cnpj/build/cpf.js';
import 'cpf_cnpj/build/cnpj.js';
import '../webapp/js/blockly';
import 'cronapi-js/dist/cronapi.min.js';
import 'cronapp-framework-js/dist/js/app.js?type=withAuth';
import 'cronapp-framework-js/dist/js/controllers.js';
import 'cronapp-framework-js/dist/js/services.js';
import 'cronapp-framework-js/dist/js/LocaleService.js';
import 'cronapp-framework-js/dist/js/LanguageSelectDirective.js';
import 'cronapp-framework-js/dist/js/directives.js';
import 'cronapp-framework-js/dist/js/filters.js';
import 'cronapp-framework-js/dist/js/reports/parameters.controller.js';
import 'cronapp-framework-js/dist/js/reports/reports.service.js';
import '../webapp/js/custom.controllers';
import 'cronapp-common-js/dist/js/parser.js';
import 'cronapp-common-js/dist/js/datasource/datasource.js';
import 'cronapp-common-js/dist/js/odata-filter-parser.js';
import 'cronapp-common-js/dist/js/pouchdb.min.js';
import 'cronapp-common-js/dist/js/pouchdb.find.min.js';
import 'cronapp-framework-js/dist/components/js/jquery.mask.min.js';
import 'cronapp-framework-js/dist/components/js/jquery.inputmask.bundle.js';
import 'cronapp-framework-js/dist/js/upload.service.js';
import 'cronapp-framework-js/dist/components/js/format.min.js';
import '../webapp/js/system-events.js';
import 'cronapp-framework-js/dist/components/js/qrcode.js';
import '../webapp/js/dataSourceMap.js';
import 'cronapp-lib-js/dist/js/tinymce/plugins/tinymce/tinymce.min.js';
import 'cronapp-lib-js/dist/js/tinymce/plugins/angular-ui-tinymce/dist/tinymce.min.js';
// import 'cronapp-lib-js/dist/js/kendo-ui/js/kendo.all.fixed.js';
// import 'cronapp-lib-js/dist/js/kendo-ui/js/cultures/kendo.culture.pt-BR.min.js';
// import 'cronapp-lib-js/dist/js/kendo-ui/js/jszip.min.js';
import 'cronapp-common-js/dist/js/parser.js';
import 'ui-select/dist/select.min.js';
// import 'cronapp-lib-js/dist/js/kendo-ui/js/timezones/kendo.timezones.min.js';

export default (app = {});
